apiVersion: v1
kind: Service
metadata:
  name: crmdbservice

spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30001
  selector:
      name: mycrmdb
      app: mycrmdb-cust1
